
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ant?characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongo:
      uri: mongodb://localhost:27017/test
logging:
  level:
    com.zwl.learn: debug
hbase:
  config:
    hbase.zookeeper.quorum: hbase01
    hbase.zookeeper.port: 2181
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8888
